### ISSUE TITLE
test fails with  EPERM: operation not permitted, mkdir 'C:\source'

### ISSUE THREAD

**Issue by webmutation** [antonybudianto/angular2-starter#149]
[19:20:14] Remapping coverage to TypeScript format...
C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\mkdirp\index.js:90
                    throw err0;
                    ^

Error: EPERM: operation not permitted, mkdir 'C:\source'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at sync (C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\mkdirp\index.js:71:13)
    at sync (C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\mkdirp\index.js:77:24)
    at sync (C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\mkdirp\index.js:77:24)
    at Function.sync (C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\mkdirp\index.js:77:24)
    at SyncFileWriter.extend.writeFile (C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\istanbul\lib\util\file-writer.js:55:16)
    at FileWriter.extend.writeFile (C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\istanbul\lib\util\file-writer.js:147:23)
    at HtmlReport.Report.mix.writeFiles (C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\istanbul\lib\report\html.js:479:16)
    at C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\istanbul\lib\report\html.js:484:22
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\istanbul\lib\report\html.js:482:23)
    at HtmlReport.Report.mix.writeReport (C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\istanbul\lib\report\html.js:566:14)
    at C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\remap-istanbul\lib\writeReport.js:77:22
    at C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\node_modules\amdefine\amdefine.js:125:34
    at nextTickCallbackWith0Args (node.js:420:9)
npm ERR! Test failed.  See above for more details.

**Comment by antonybudianto** [comment]
looks like you need admin command prompt if you're on windows

**Comment by webmutation** [comment]
Why is it trying to create a directory? Don't really understand... and why is it trying to do that at root, instead of creating a temp directory in the base of the project. 

Its strange because I have remap-istambul running on my setup without any issues and without requiring Admin rights.

**Comment by kennyhyun** [comment]
I see you're using 

    C:\DEV\Angular2 Unit Tests Projects\angular2-starter-rc6-coverage\

which is including space. 
mkdirp is  for creating dirs including parent dirs. 
it can be problematic. please try remove space on it.

**Comment by webmutation** [comment]
well you closed it but it was not fixed ;) with no space it still has the same error

**Comment by antonybudianto** [comment]
sorry I closed it due to no response

**Comment by webmutation** [comment]
I think there is a bug on the Karma plugin related to this, so its a bit strange.

**Comment by antonybudianto** [comment]
i see, you can post the issue there and stackoverflow too
