### ISSUE TITLE
Can't start freshly cloned project.

### ISSUE THREAD

**Issue by MKraust** [antonybudianto/angular2-starter#199]
## Issue Overview
<Please explain the issue overview here, short but concise and to-the-point>
Can't start freshly cloned project.

## Issue Description
<Please explain the issue in details>
Here are cmd log and npm-debug.log file.

```
D:\Projects\ng-starter2>npm start
 
> angular2-starter@1.0.1 start D:\Projects\ng-starter2
> gulp serve-dev

============ Angular 2 Starter ============
Current environment: development
- Change environment via --env or NODE_ENV
- env.json is not detected. You can create one on project root
===========================================
[23:56:01] Using gulpfile D:\Projects\ng-starter2\gulpfile.js
[23:56:01] Starting 'serve-dev'...
[23:56:01] Starting 'sass'...
[23:56:01] Starting 'env'...
[23:56:01] Finished 'serve-dev' after 18 ms
[23:56:01] src/app/shared/constant/env.ts is generated successfully
[23:56:01] Finished 'env' after 30 ms
[23:56:01] Starting 'tsc-app'...
[23:56:02] Finished 'sass' after 571 ms
D:/Projects/ng-starter2/node_modules/@angular/common/src/pipes/async_pipe.d.ts(44,38): error 2304: Cannot find name 'Promise'.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular2-starter@1.0.1 start: `gulp serve-dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-starter@1.0.1 start script 'gulp serve-dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve-dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-starter
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\ng-starter2\npm-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-starter@1.0.1~prestart: angular2-starter@1.0.1
6 silly lifecycle angular2-starter@1.0.1~prestart: no script for prestart, continuing
7 info lifecycle angular2-starter@1.0.1~start: angular2-starter@1.0.1
8 verbose lifecycle angular2-starter@1.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-starter@1.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Projects\ng-starter\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\OpenServer\modules\git\bin;C:\OpenServer\modules\php\PHP-7.0-x64;C:\OpenServer\modules\wget\bin;C:\OpenServer\modules\cron;C:\OpenServer\modules\database\MySQL-5.7-x64\bin;C:\OpenServer\modules\database\MongoDB-3.4-x64;C:\OpenServer\modules\memcached\Memcached-1.4-x64;C:\OpenServer\modules\http\Nginx-1.11;C:\OpenServer\modules\http\Apache-PHP-7-x64\bin;C:\OpenServer\modules\sendmail;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Users\kraus\AppData\Local\Microsoft\WindowsApps;C:\Users\kraus\AppData\Roaming\Composer\vendor\bin;C:\Users\kraus\AppData\Local\atom\bin;C:\Users\kraus\AppData\Roaming\npm
10 verbose lifecycle angular2-starter@1.0.1~start: CWD: D:\Projects\ng-starter
11 silly lifecycle angular2-starter@1.0.1~start: Args: [ '/d /s /c', 'gulp serve-dev' ]
12 silly lifecycle angular2-starter@1.0.1~start: Returned: code: 1  signal: null
13 info lifecycle angular2-starter@1.0.1~start: Failed to exec start script
14 verbose stack Error: angular2-starter@1.0.1 start: `gulp serve-dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-starter@1.0.1
16 verbose cwd D:\Projects\ng-starter
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error angular2-starter@1.0.1 start: `gulp serve-dev`
22 error Exit status 1
23 error Failed at the angular2-starter@1.0.1 start script 'gulp serve-dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve-dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

## Reproducables
<Please explain the way to reproduce your issue, or even better with Plunker link>
```
git clone https://github.com/antonybudianto/angular2-starter.git ng-starter2
npm install
npm start
```

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 	|
| **Node version**     	| 6.10.0   	|
| **NPM Version**      	| 3.10.10   	|

**Comment by antonybudianto** [comment]
Looks like some packages break semver rules, you can use Yarn for installation

**Comment by Emerceen** [comment]
+1

**Comment by antonybudianto** [comment]
I've fixed the dependencies, please review it, thanks! @MKraust  @Emerceen

**Comment by MKraust** [comment]
Yep. It's okay now. Thank you!
