### ISSUE TITLE
gulp-inject syntax error!

### ISSUE THREAD

**Issue by rakeen** [antonybudianto/angular2-starter#54]
<Have you checked issues section which may have your similar issue?>
<Please take your time filling these required information for posting issue>

## Issue Overview
<Please explain the issue overview here, short but concise and to-the-point>
`gulp` is not running! Error in `gulp-inject` package.

## Issue Description
<Please explain the issue in details>
I tried to run the project,
and got this error  

```
\angular2-starter\node_modules\gulp-inject\src\inject\index.js:127`
      startTag,
              ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (\angular2-starter\node_modules\gulp-inject\index.js:4:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

\simple_ng2_app_test\angular2-starter>
```

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 7 	|
| **Node version**     	| 0.12.3   	|
| **NPM Version**      	| 3.7.1    	|
| **Environment**       | Browser          |
| **gulp-inject**       | 4.0.0          |

**Comment by antonybudianto** [comment]
Hi, recently I mentioned it in [wiki](https://github.com/antonybudianto/angular2-starter/wiki) that I drop the support for Node `v0.x.x` since new `gulp-inject` also require Node `v4.x.x`
Please update your node version or downgrade `gulp-inject` to `gulp-inject@3`
